apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: urd1c7mpm-go 
  janus-idp.io/tekton: urd1c7mpm-go
  backstage.io/kubernetes-id: urd1c7mpm-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: urd1c7mpm-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml