apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: urd1c7mpm-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: urd1c7mpm-go 
  name: urd1c7mpm-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: urd1c7mpm-go 
